# ref https://github.com/oke-aditya/image_similarity/blob/9ee94f0509d590178b2fb8f547b111a8cba6ad69/.github/workflows/pypi-release.yml
name: Upload pypi package release

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install wheel
        # python -m pip install --upgrade pip
        # pip install setuptools wheel twine
        # pipenv install --dev twine
        # pipenv shell
        # python setup.py sdist bdist_wheel
    - name: Build
      run: |
        python3 setup.py sdist --formats=zip
        #twine upload dist/*
    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


# NOTE : Util now
# modify ```version``` parameter in setup.cfg.

# ```
# version = 
# ```

# ```
# pipenv shell
# pipenv install --dev twine
# python3 setup.py sdist --formats=zip
# twine upload dist/*
# ```
